### ISSUE TITLE
uploaded data goes into black hole

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-dashboard#126]
logged into dev-dashboard as testing. created site. created obs. uploaded `observation_1h.csv` file from workshop repo. returned to obs page and no data is shown.

**Comment by lboeman** [comment]
Ah yeah, the current endpoints only allow for start/end point selection so we're just requesting the past three days. If that data doesn't exist, nothing gets plotted. We're going to need add some way of determining the available data from the API before that can be remedied.

Opened https://github.com/SolarArbiter/solarforecastarbiter-api/issues/168

**Comment by lboeman** [comment]
I should add that this worked before because we were requesting *all* of the data and only plotting the last three days. Hence the slow page loads.

**Comment by lboeman** [comment]
This was closed in #277. Most recent data/forecast should be displayed when the page loads.
