### ISSUE TITLE
Should be able to view an incomplete report without 'read_values' permissions

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-dashboard#134]
We should be able to read the report metrics ('read' permission) and without reading the report values ('read_values' permission) on the dashboard. This probably requires changes to API and/or core as well.

**Comment by lboeman** [comment]
Adding notes about permissions implications. Much of this will come down to handling errors in core. 
 Moving away from using the Core api library for reports in the dashboard could simplify things.

related issue: https://github.com/SolarArbiter/solarforecastarbiter-core/issues/281

Permissions and impacts on final report viewing/rendering(as of report refactoring):

- *('read', 'report')* User can view report metadata, and all metrics. The prerendered metadata table of all obs/fx pairs will be visible in the rendered report. So perhaps we need a warning that "sharing a report exposes certain fields from your object's metadata".

- *('read', 'fx/obs')*  - Required for timeseries/scatter plots. `solarforecastarbiter.io.api.APISession.process_report_dict` iterates through each object in object_pair, and builds the corresponding  Datamodel object. This will cause a failure when the user tries to load a report page. 

- *('read_values', 'report') and ('read_values', 'fx/obs')* Required for timeseries and scatter plots. In the core api module, processed fx/obs are loaded from the `values` key of the report. When the final templating is performed in `solarforecastarbiter.reports.template.py` missing permissions for read_values. When a user does not have `read_values` on a given fx/observation, a warning is printed in place of timeseries and scatter plots.
