### ISSUE TITLE
Move upload data controls to obs/fx/cdf pages

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-dashboard#196]
After #184, it was brought up that having a separate page for uploads is awkward. We should move the upload ability to the same pages, and ideally provide a sample document for format reference and return the user to view the data they just uploaded.

**Comment by lboeman** [comment]
Considering #198 (adding a note about rounding values). Do we want to retain the upload pages to provide information like this? 

If we'd still rather just have an 'Upload Data' button with a file selector, I can put some more thought into how to prompt a user with these details.

**Comment by wholmgren** [comment]
Maybe the upload button could move to a foldable upload section at the bottom of each page. Maybe move delete all the way to the bottom.
