### ISSUE TITLE
make page titles more descriptive

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-dashboard#202]
like we did in https://github.com/SolarArbiter/SolarArbiter.github.io/pull/130

**Comment by lboeman** [comment]
Would the current object's name be sufficient? And maybe just 'Observations' etc for the listing pages.

As a note to myself for tackling this later, Need to reorganize to consistently provide the current object's metadata to templating.

**Comment by wholmgren** [comment]
Yes, that's fine with me.
