### ISSUE TITLE
support probabilistic reports

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-dashboard#215]
Might require a different page.

Users should be able to 

1. select `ProbabilisticForecastConstantValue` objects for metrics like Brier score
2. select `ProbabilisticForecast` objects for metrics like CRPS
3. select an appropriate reference forecast 

Doing 1 and 2 in the same report would be really nice, but if it's too hard then we can reconsider. 3 would require only 1 or 2.

core PR: https://github.com/SolarArbiter/solarforecastarbiter-core/pull/367

**Comment by wholmgren** [comment]
@awig @dplarson maybe you guys can log in to the dev-dashboard using the testing account and think about this.

**Comment by lboeman** [comment]
Adding a link to the relevant issue for supporting probabilistic forecasts.
https://github.com/SolarArbiter/solarforecastarbiter-core/issues/266

**Comment by wholmgren** [comment]
woot.

**Comment by awig** [comment]
Congrats @wholmgren @lboeman 
I tried running a dev-dashboard Prob Forecast report but my user on the dev-dashboard doesn't have permission.

**Comment by wholmgren** [comment]
I think you’d need to login with the testing account.

**Comment by awig** [comment]
> I think you’d need to login with the testing account.
😑 

I took a look at the already created reports. Very nice!

I'll send you an email with some thoughts.
