### ISSUE TITLE
add recompute report button somewhere

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-dashboard#224]
perhaps at the top of the report page? Should probably also catch errors when trying to render the report here https://github.com/SolarArbiter/solarforecastarbiter_dashboard/blob/7f538d90331e27bc145a623aebef580738056462/sfa_dash/blueprints/reports.py#L163

**Comment by lboeman** [comment]
What errors are you seeing pop up at that line?

**Comment by alorenzo175** [comment]
Trying to load one of the old reports from prod dashboard with new datamodel raises an error in creating the report from the json dict

**Comment by wholmgren** [comment]
related: add indicator to a report that is currently being recomputed
