### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-dashboard#244]
to solarforecastarbiter-dashboard to be consistent with core and api. According to https://help.github.com/en/github/administering-a-repository/renaming-a-repository everything should work without intervention. Objections @lboeman ?

**Comment by lboeman** [comment]
Nope! That's  works with me. Looks like we just need to update the GH triggers for openshift and our own local upstreams.

**Comment by alorenzo175** [comment]
And it is done
