### ISSUE TITLE
Colon symbol not supported in site names?

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-dashboard#253]
While creating a new site using the dashboard, I ran into the issue that the colon symbol is not allowed when defining a site name (e.g. "some site, CA: 1 MW tracking PV" returns a "invalid string" error, but "some site, CA 1 MW tracking PV" works). I imagine this is documented somewhere, but it wasn't immediate obvious to me that the colon was the issue based on the error message. Therefore, would it be worthwhile to modify either the error message (or the help menu that appears when you click the question mark symbol) for "Name" to clarify any constraints on allowed names?

For example, something like "Names may contain the follow symbols: `a-z`, `A-Z`, `0-9`, `,`"?

**Comment by lboeman** [comment]
Thanks for the feedback David. I'll add some validation to the form so we don't have to go through the api roundtrip with an unhelpful error message.
