### ISSUE TITLE
Clarification and/or validation of file size limits for uploads?

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-dashboard#254]
While trying to upload observation data for a new site using the dashboard, I ran into an "Internal Server Error" ~30-seconds after starting the upload of a ~9 MB CSV file. While this may just be a one-time error, it made me think that it may be worthwhile to do some testing with files of different sizes in order to confirm potential limitations for uploading data files and provide some documentation on the subject. For example, telling users to chunk data files if the total data is over X MB (e.g. `observation.csv` becomes `observation_1.csv`, `observation_2.csv`, etc.) or advising users to upload big data files via the API instead of the dashboard (if it turns out the API is more robust for large files).

Just a thought.

**Comment by dplarson** [comment]
Notes:
- I was able to reproduce the result using the same file in both Chrome and Firefox
- Reducing the file from ~9 MB to ~6 MB (from 3-years of 5-min data to 2-years of 5-min data) allowed the data upload to succeed

**Comment by wholmgren** [comment]
Thanks for the report @dplarson. I'd like to think we could handle a 100 MB file. Whatever the limitation is, we should also document it in the x years of y-minute data that you've described.
