### ISSUE TITLE
Deterministic forecast reports fail with more than 3 forecasts?

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-dashboard#255]
Sorry to open another issue (and please tell me if you'd prefer I communicate these issues a different way, e.g., via email):

In testing the dashboard, I've run into an issue where creating a deterministic forecast report with 1, 2 or 3 forecasts works fine, but adding a 4th forecast causes the report to fail. This is with everything else kept constant (same site, same observation data, same metrics, same time period, same quality flags, etc.):

<img width="1180" alt="Screen Shot 2020-05-19 at 5 39 27 PM" src="https://user-images.githubusercontent.com/1169109/82392085-d2c02100-99f7-11ea-854f-cd4f8a3208a3.png">

I haven't done an exhaustive test, but I have tried a couple different combinations of the forecasts (e.g. 1h-ahead + 4h-ahead + 6h-ahead and 1h-ahead + 4h-ahead + 24h-ahead both work) and get the same result.

Additional info that may be helpful:
- time period for report: 2-years (2016-01-01T00:00Z to 2018-01-01T00:00Z)
- observation data: 2-years at 5-minute resolution (AC power) available
- forecasts: 3-years at 1-hour resolution available
- metrics: MAE, MBE, RMSE, NMAE, NMBE, NRMSE
- categories: defaults
- quality flags: night values

Any ideas?

**Comment by alorenzo175** [comment]
Likely that the report generation job takes too long or uses too much memory so it gets killed. I'll take a look tomorrow and maybe tweak a few things.
________________________________

**Comment by wholmgren** [comment]
Hm, can you add the 4th report if you specify a shorter time period?

GitHub issues are good for me.

**Comment by dplarson** [comment]
> Hm, can you add the 4th forecast to the report if you specify a shorter time period?

Specifying 1 year (instead of 2) with 4 forecasts (and everything else held constant) results in the report completing successfully. Which I imagine means this is indeed either a job timeout or memory issue as Tony suggested.

**Comment by alorenzo175** [comment]
I think this should have been fixed in beta6 with https://github.com/SolarArbiter/solarforecastarbiter-api/commit/2dd76f0c01bad3b1120e2697d87404cfff6dd0bf and some adjustments to the deployment like having a dedicated api for the workers
