### ISSUE TITLE
Show date range in Observation Metadata section

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/solarforecastarbiter-dashboard#256]
Feel free to ignore this suggestion if it's not feasible, significantly increases latency, etc., but:

I think it would be helpful to display the available time range (start and end) in the "Observation Metadata" when viewing an Observation on the dashboard. So when you navigate to an Observation, users can immediately see the range of data that is available, particularly for "frozen" datasets (i.e. datasets that are not automatically updated with new data). Without such info, users have to either (iteratively) guess time ranges to plot or pick an excessively long time range (e.g. last 5 or 10 years) to figure out what data is available.

Something like this:

<img width="879" alt="Screen Shot 2020-05-20 at 5 42 31 PM" src="https://user-images.githubusercontent.com/1169109/82511223-9b1dab80-9ac1-11ea-9f7a-970b954ad883.png">

**Note:** I am not suggesting we auto-populate the graph when the page loads; this is solely to list the start and end dates of the data to give users a clearer starting point for exploring data.

My (somewhat naive) understanding is that this would require 2 steps: 1) a call to the DB via the API to get the start and end times (each time the page is loaded?) and 2) formatting the info into the page.

**Comment by wholmgren** [comment]
@lboeman this should be straightforward since we now have the API call available, right?

**Comment by lboeman** [comment]
Yeah. We can implement both adding the available time range to the metadata and displaying the 3 most recent days of data by default!
