### ISSUE TITLE
Integrate climate zones into dashboard

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-dashboard#279]
We can start by displaying the list of climate zones for each site on the metadata pages maybe after #275. Then I think we need to be able to filter sites based on the zone.

Maybe eventually we display a [leaflet](https://leafletjs.com/examples/geojson/) map of the zones where you can also click on a zone to download the geojson, and  maybe put all the sites on there as well. 

not sure what else for 1.0

**Comment by lboeman** [comment]
I can take care of this. @wholmgren also suggested removing lat/lon from sites list and replace with climate zones. That seems like a better use of space on the page than lat/lon.
