### ISSUE TITLE
Add cost to report creation

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-dashboard#289]
Not in core or API yet, but https://github.com/SolarArbiter/solarforecastarbiter-core/blob/7626b9ed1e46d6552df00dbf8cffab0fe2b69dba/solarforecastarbiter/tests/data/report_metadata.json can be used as a jumping off point for an idea of what the JSON from teh API will need to look like

**Comment by lboeman** [comment]
@alorenzo175 Does the `cost` field of report parameters only get used if a user selects the `cost` metric?

**Comment by alorenzo175** [comment]
currently, yes.
