### ISSUE TITLE
Add controls for Forecast filling

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-dashboard#292]
In support of https://github.com/SolarArbiter/solarforecastarbiter-core/pull/493 
Will need a way for users to define how to fill missing forecasts.

**Comment by wholmgren** [comment]
Perhaps something like:

## Missing Forecast Logic

All missing or NaN forecast intervals should be:
[radio] dropped from the analysis 
[radio] filled with [enter number, enforce with javascript]
[radio] filled forward with the last valid forecast value
