### ISSUE TITLE
Report javascript error for probabilistic forecasts

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-dashboard#300]
![image](https://user-images.githubusercontent.com/4625457/86186920-44a78200-baef-11ea-9429-75700148adad.png)

**Comment by alorenzo175** [comment]
And the CRPS drop downs don't work, maybe related?

**Comment by alorenzo175** [comment]
from https://dev-dashboard.solarforecastarbiter.org/reports/60f746a8-b7f7-11ea-b06d-0a580a8200f2, but no guarantees if database is wiped

**Comment by lboeman** [comment]
Just so it doesn't get lost, cause of the error is using the forecast names directly, and special characters are being escaped with HTML codes, causing invalid selectors. e.g. #year_bs_Albuquerque_NM_Day_Ahead_GEFS_ac_power_Prob(f_&lt;=_x)_=_10.0%

**Comment by wholmgren** [comment]
Should we instead modify the core templating so that problematic ids are not created? Probably just a matter of adding `replace('<=', 'lte')` where the ids are created. Not sure if `/, ^, %, =` would also cause problems.

**Comment by lboeman** [comment]
> Should we instead modify the core templating so that problematic ids are not created? Probably just a matter of adding `replace('<=', 'lte')` where the ids are created. Not sure if `/, ^, %, =` would also cause problems.

That's probably the way to go. I haven't touched the code that utilizes the ids in a minute, but it might require some work to maintain relationships between an object's actual name and the cleaned id-safe version.
