### ISSUE TITLE
inconsistent "create new..." formatting

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-dashboard#301]
Create New Report and Create New Aggregate should look like the others. Easy fix @lboeman?

<img width="606" alt="Screen Shot 2020-07-01 at 11 21 23 AM" src="https://user-images.githubusercontent.com/4383303/86278367-1d06f700-bb8d-11ea-814c-d406d7381e99.png">
<img width="599" alt="Screen Shot 2020-07-01 at 11 21 12 AM" src="https://user-images.githubusercontent.com/4383303/86278369-1e382400-bb8d-11ea-840c-e30e79d5c31a.png">
<img width="643" alt="Screen Shot 2020-07-01 at 11 21 02 AM" src="https://user-images.githubusercontent.com/4383303/86278372-1ed0ba80-bb8d-11ea-9a28-f5283888c3b2.png">
<img width="587" alt="Screen Shot 2020-07-01 at 11 20 49 AM" src="https://user-images.githubusercontent.com/4383303/86278374-1f695100-bb8d-11ea-88e7-70af12c7190b.png">
<img width="556" alt="Screen Shot 2020-07-01 at 11 20 41 AM" src="https://user-images.githubusercontent.com/4383303/86278376-2001e780-bb8d-11ea-913e-82a656ffce66.png">
<img width="706" alt="Screen Shot 2020-07-01 at 11 20 30 AM" src="https://user-images.githubusercontent.com/4383303/86278378-2001e780-bb8d-11ea-83d6-96376881b68f.png">

**Comment by lboeman** [comment]
Yep!

**Comment by alorenzo175** [comment]
And should be Create **New** CDF Forecast?
