### ISSUE TITLE
don't allow sites without modeling_parameters to have power, poa observations

### ISSUE THREAD

**Issue by lboeman** [SolarArbiter/solarforecastarbiter-dashboard#338]
https://github.com/SolarArbiter/solarforecastarbiter-api/issues/241
limit forecast variables at sites without modeling parameters.

**Comment by wholmgren** [comment]
should also make it clear when creating a site that power and POA observations require a power plant.

**Comment by lboeman** [comment]
Just to double check, the variables requiring modeling parameters are: 
AC power, DC power, curtailment, POA, and net load

**Comment by wholmgren** [comment]
AC power, DC power, curtailment, POA, and availability
