### ISSUE TITLE
double display of "report deleted successfully"

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-dashboard#397]
firefox, mac... haven't confirmed behavior with other browsers

<img width="1175" alt="Screen Shot 2020-12-02 at 8 18 44 PM" src="https://user-images.githubusercontent.com/4383303/100959515-af644b80-34db-11eb-8149-c8f8240e2472.png">

**Comment by lboeman** [comment]
closed by #415
