### ISSUE TITLE
site creation page should have hints for net load, wind power

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-dashboard#403]
Not sure where to put this. maybe the site type help box? Something like "`<br><br>`For load or wind power plants, choose Power Plant, set DC Capacity to be equal to AC capacity, and set temperature coefficient, surface tilt, and surface azimuth to 0."

We could also link to a documentation page with more detail.

**Comment by lboeman** [comment]
Perhaps we just adjust the "Site type" selection to include "Weather Station", "Solar Power Plant", "Wind Power Plant", and just fill in those values for the user automatically while hiding the ones that don't matter for wind.  Would be a little confusing to the end user to eventually land at a site that displays the extra parameters that aren't useful to them until we can update to further support wind.
