### ISSUE TITLE
tooltip text

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-dashboard#60]
Some of the tooltip text needs improvement/fixes. This issue is just a reminder for now.

**Comment by wholmgren** [comment]
on the site page, if "weather station" selected, clicking the ? on the boxes in PV modeling parameters appears to force a page reload. Also the section label style seem broken

<img width="861" alt="Screen Shot 2020-10-21 at 2 18 04 PM" src="https://user-images.githubusercontent.com/4383303/96789472-1d303a00-13aa-11eb-9cac-143f69a55253.png">

**Comment by wholmgren** [comment]
@lboeman I don't see a problem with any of the other tooltips so maybe they were updated at some point. let's fix this bug for rc4 and call it good.

**Comment by lboeman** [comment]
Sounds good. I'm looking into it. I've narrowed it down to a firefox problem, should have a fix shortly.
