### ISSUE TITLE
Add map with all sites

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/solarforecastarbiter-dashboard#75]
Our static webpage includes a map of [reference data](https://solarforecastarbiter.org/referencedata/) sources using a "Google My Maps" map. 

For the dashboard, it would be nice to use the [Google Maps Javascript API](https://developers.google.com/maps/documentation/javascript/tutorial) to dynamically create a map that shows all sites that the user has access to (including the reference data sites).

**Comment by alorenzo175** [comment]
yes, although maybe use leaflet with a free tile provider and avoid the api limit or paying

**Comment by wholmgren** [comment]
duplicate of #286
